# Maven
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
pool:
  vmImage: 'ubuntu-16.04' # Hosted Ubuntu 1604
  demands: maven

steps:
- task: Maven@3
  displayName: 'Maven app/pom.xml'
  inputs:
    mavenPomFile: 'pom.xml'
    codeCoverageToolOption: Cobertura
    options: '-DskipTests'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo "jobName=$(Build.DefinitionName)" >> $(build.artifactstagingdirectory)/environment-variables.txt
      echo "buildNumber=$(Build.BuildId)" >> $(build.artifactstagingdirectory)/environment-variables.txt
      echo "repoName=$(Build.Repository.Name)" >> $(build.artifactstagingdirectory)/environment-variables.txt
      echo "branchName=$(Build.SourceBranchName)" >> $(build.artifactstagingdirectory)/environment-variables.txt
      echo "repoURL=$(Build.Repository.Uri)" >> $(build.artifactstagingdirectory)/environment-variables.txt
      echo "commitID=$(Build.SourceVersion)" >> $(build.artifactstagingdirectory)/environment-variables.txt
      echo "BlackDuckProject=$(Build.DefinitionName)" >> $(build.artifactstagingdirectory)/environment-variables.txt
      echo "BlackDuckVersion=1" >> $(build.artifactstagingdirectory)/environment-variables.txt

